### ISSUE TITLE
Android documentation missing/incomplete for smallIcon

### ISSUE THREAD

**Issue by mikehardy** [notifee/documentation#7]
@mikehardy No worries, actual I wasn't able to find the `smallIcon` field in the documentation until I go through someone else's example on other issues and took a bit in-depth into looking at the library's JS file to reached where I at. 

Would be great if can update some relevant information about the default `ic_launcher` required somewhere in this https://notifee.app/react-native/docs/displaying-a-notification would be great but I guess it's not really urgent as of now. 

Thanks for the follow up btw. Cheers.

_Originally posted by @MystL in https://github.com/notifee/react-native-notifee/issues/149#issuecomment-696180948_

**Comment by helenaford** [comment]
updated docs 👍
