### ISSUE TITLE
Documentation: `./gradlew assembleRelease` fails, `./gradlew :app:assembleRelease` needed

### ISSUE THREAD

**Issue by mikehardy** [notifee/documentation#8]
As the title indicates, to compile this successfully via command line for Android you have to specify the module-prefixed gradle target, not the generic one.

Why? I have no idea.

But if you don't! You will have a compile failure: 
- https://github.com/notifee/react-native-notifee/issues/151
- https://github.com/notifee/react-native-notifee/issues/68 

I do not know where the best page to document this is but future people will waste their time and be frustrated unless we document it

**Comment by evelant** [comment]
@mikehardy Is this somehow possibly related to these issues where the js bundle fails to get copied into the apk/aab? https://github.com/react-native-community/upgrade-support/issues/38 and https://github.com/facebook/react-native/issues/29398

When using android gradle plugin 4+ it seems there might be an issue with task ordering and/or choosing the correct files to add to the apk. Is it possible that this is causing the build problems in this issue as well?

Sorry if this is barking up the wrong tree, I don't have much experience (yet) with gradle and the details of the android build system.

**Comment by mikehardy** [comment]
@AndrewMorsillo I think those are unrelated - this is a separate part of things entirely, long before anything related to bundles happens

**Comment by SandroMachado** [comment]
@mikehardy after investigating this the best option that I'm seeing it to upload the core library to the maven repository or host this in a maven repository created by you. The problem with this is that this is a library with an `aar` as peer dependecy.

Another alternative would be adding [these](https://stackoverflow.com/a/60888941/3482000) instructions to the readme.

**Comment by mikehardy** [comment]
1. uploading to maven repo, assume this is not happening

2. as mentioned 3 other libraries import the library differently and add a local directory as a local maven repo (similar to your now-closed PR #257)

Given 1 is not happening (or at least: definitely not right now), I do not see why following the lead of multiple other (successful) projects is a problem?

What am I missing?

**Comment by SandroMachado** [comment]
They create a local maven repository: https://github.com/tosbaha/jsc-android/blob/master/dist/org/webkit/android-jsc/maven-metadata.xml

We need to do that for this also :(

**Comment by mikehardy** [comment]
Now I see what you mean! Thank you for persisting on this, I understand it much better now.

My other project reference(s) do the same https://github.com/transistorsoft/react-native-background-fetch/tree/master/android/libs/com/transistorsoft/tsbackgroundfetch

So that appears to be the correct path (for a local aar install, excluding some external network-based maven repo)

**Comment by helenaford** [comment]
Note has been added to the docs (https://notifee.app/react-native/docs/environment-support#additional-requirements). Will keep this open until the fix is implemented where notifee uses a local maven repository.
